---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars:
    pkg_name: httpd
    username: Angel
  tasks:
    - name: Creating user
      user:
        name: "{{ username }}"
        comment: Angel Linux
        shell: /bin/bash
          #when: ansible_os_family == "Debian"
    - name: create a file
      file:
       path: /tmp/ansible.txt
       state: touch
       mode: '0600'  
    - name: create a file
      file:
       path: /tmp/dir
       state: directory
       mode: '0777'
    - name: install apache
      yum:
        name: "{{ pkg_name }}"
        state: present
    - name: install finger
      package:
        name: "{{ item }}"
        state: present
      with_items:
        wget
        vim
            

