---
- name: Static App Deployment 
  hosts: devserver
  become: yes
  ignore_errors: True
  tasks:
  - name: installing packages
    yum:
      name: "{{item}}"
      state: present  
    when: ansible_distribution == "Amazon"  
    loop: 
       - httpd
       - unzip
       - wget
  - name: Getting app content
    get_url:
      url: https://github.com/utrains/static-resume/archive/refs/heads/main.zip
      dest: /tmp/main.zip
  - name: unarchiving content
    unarchive:
      src: /tmp/main.zip
      dest: /tmp
      remote_src: yes
  - name: copy file to html
    copy:
      src: /tmp/static-resume-main/iPortfolio/
      dest: /var/www/html/
      remote_src: yes
      follow: yes
  - name: starting apache
    service:
      name: httpd
      state: started
      enabled: yes

