---
- hosts: qaserver
  become: yes
  ignore_errors: yes
  tasks:
  - name: install packages
    package: 
      name: "{{ item }}"
      state: present
    with_items:
      - unzip
      - wget
      - httpd
  - name:
